# Generated by Django 3.2 on 2022-07-20 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='group_id')),
                ('group_name', models.CharField(default='group', max_length=45, verbose_name='group_name')),
                ('code', models.CharField(default='EYWANKSSBZJSDEZRCQBVRGQKQQOUGD', editable=False, max_length=45, unique=True, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='meeting_id')),
                ('metting_name', models.CharField(default='metting', max_length=45, verbose_name='metting_name')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='participant_id')),
                ('money', models.IntegerField(default=0)),
                ('is_clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='receipt_id')),
                ('receipt_name', models.CharField(default='receipt', max_length=45, verbose_name='receipt_name')),
                ('total', models.IntegerField(default=0)),
                ('is_clear', models.BooleanField(default=False)),
                ('meeting_id', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='groups.meeting')),
            ],
        ),
    ]
