# Generated by Django 3.2 on 2022-07-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='group_id')),
                ('group_name', models.CharField(default='group', max_length=15, verbose_name='group_name')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='code')),
                ('leader', models.ForeignKey(db_column='leader', on_delete=django.db.models.deletion.CASCADE, related_name='leader_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_FK', models.ForeignKey(db_column='group_FK', on_delete=django.db.models.deletion.CASCADE, related_name='group_in', to='groups.group')),
                ('user_FK', models.ForeignKey(db_column='user_FK', on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='member_in_group', through='groups.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
