# Generated by Django 3.2 on 2022-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='group', max_length=15, verbose_name='group_name'),
        ),
    ]
