# Generated by Django 3.2 on 2022-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='metting_name',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='metting', max_length=45, verbose_name='meeting_name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='TRDGIWXNNLLWKTBTWDAVMNQVNOFNNC', editable=False, max_length=45, unique=True, verbose_name='code'),
        ),
    ]
