# Generated by Django 3.2 on 2022-07-29 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20220720_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_name',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='aVFmd3VR', editable=False, max_length=45, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='create_dt',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
