# Generated by Django 3.2 on 2022-07-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='SFMyTXJT', editable=False, max_length=45, unique=True, verbose_name='code'),
        ),
    ]
