# Generated by Django 3.2 on 2022-07-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='L1BqSFk0', editable=False, max_length=45, verbose_name='code'),
        ),
    ]
