# Generated by Django 3.2 on 2022-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='user_id'),
        ),
    ]
