# Generated by Django 3.2 on 2022-07-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
